name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt || true
          pip install ruff black pytest || true

      - name: Lint
        run: make lint

      - name: Tests
        env:
          PYTHONPATH: src
        run: pytest -q tests
